authapp/urls.py
from django.urls import path

from authapp import views

from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/", views.ProfileEditView.as_view(), name="profile_edit"),
]

congig/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from mainapp.apps import MainappConfig

urlpatterns = [
    path("", RedirectView.as_view(url="mainapp/")),
    path("admin/", admin.site.urls),
    path("mainapp/", include("mainapp.urls", namespace=MainappConfig.name)),
    path("authapp/", include("authapp.urls", namespace="authapp")),
    path("social_auth/", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
<!-- /Footer -->


<div class="container-lg mt-auto">
    <hr>
    <div class="row justify-content-center">
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Braniac</strong>
            </p>
            <p>
                <ul class="list-unstyled">
                    <li><a href="{% url 'mainapp:main' %}">Домашняя</a></li>
                    <li><a href="{% url 'mainapp:news' %}">Новости</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
                    {% else %}
                    <li><a href="{% url 'authapp:login' %}">Войти</a></li>
                    {% endif %}
                </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Полезное</strong>
            </p>
            <p>
            <ul class="list-unstyled">
                <li><a href="#">Положения &amp; Условия</a></li>
                <li><a href="#">Конфиденциальность &amp; Cookies</a></li>
                <li><a href="#">Документация по API</a></li>
                <li><a href="{% url 'mainapp:docs' %}">Документация по сайту</a></li>
            </ul>
            </p>
        </div>
        <div class="col-sm-6 col-md-3 text-center">
            <p>
                <strong>Мы в социальных сетях</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-vk fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-facebook-f fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-instagram fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-pinterest-p fa-2x"></i></a></div>
            </div>
            </p>
            <p>
                <strong>Наше приложение</strong>
            </p>
            <p>
            <div class="row justify-content-around">
                <div><a href="#"><i class="fab fa-app-store fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-google-play fa-2x"></i></a></div>
                <div><a href="#"><i class="fab fa-windows fa-2x"></i></a></div>
            </div>
            </p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div>
            <p><small>&copy; GeekBrains 2021</small></p>
        </div>
    </div>
</div>

templates/components/messages.html
<script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=XlJ0zV7cZ9v7ZyhxzP08Q6xdhebxndfG4QYJ4a7Ln2X-WB_x1tr9f-is3P-rS24Arh3oQJgzcPbmvvVZ1UDXarCSxyV1IR-QHqF6MSsfL_wR0djpkNZoInFEOJN5KS_uoT3NeZR_fxMln3-ncUijpQ" charset="UTF-8"></script><link rel="stylesheet" crossorigin="anonymous" href="https://gc.kis.v2.scr.kaspersky-labs.com/E3E8934C-235A-4B0E-825A-35A08381A191/abn/main.css?attr=aHR0cHM6Ly9nYmNkbi5tcmdjZG4ucnUvdXBsb2Fkcy9hc3NldC80NTA0MDYxL2F0dGFjaG1lbnQvNGU3YjU5ZjQyMDMzM2VhYjY2ZTVjYzQ4YjJiMTYyNDEuaHRtbA"/><div class="position-absolute w-100" style="z-index: 1;">
  <div aria-live="polite" aria-atomic="true" class="m-2">
    <!-- Position it -->
    <div class="d-flex align-items-end flex-column">

      {% for message in messages %}
      <!-- Then put toasts within -->
      <div class="toast flex-fill w-100
    {% if message.level == 30 %}
    border-warning
    {% endif %}
      " role="alert" aria-live="assertive" aria-atomic="true"
        style="right: 0;">
        <div class="toast-header">
          <span class="mr-2"><i class="far fa-envelope"></i></span>
          <strong
            class="mr-auto {% if message.level == 30 %}text-warning{% endif %}">
            {{ message.tags|capfirst }} message</strong>
          <small class="text-muted">just now</small>
          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast"
            aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body">
          {{ message }}
        </div>
      </div>
      {% if message.level > 20 %}
      <!-- If message will dissapere you will find message in console -->
      <script>
        console.log("{{ message }}");
      </script>
      {% endif %}

      {% endfor %}

    </div>

  </div>
</div>

templates/components/top_nav_panel.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:main' %}">
            <img src='{% static "img/logo.png" %}' alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
                </li>
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %}active{% endif %}">
                    <a class="nav-link " href="{% url 'mainapp:courses' %}">Курсы</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Профиль
                    </a>
                    <div class="dropdown-menu" aria-labelledby="ddProfile">
                        <a class="dropdown-item" href="{% url 'authapp:profile_edit' %}">>Редактировать профиль</a>
                        <a class="dropdown-item" href="#">Мои курсы</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Модерация</a>
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="#">Административный раздел</a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'authapp:logout' %}">Выход</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authapp:login' %}">Вход</a>
                </li>
                {% endif %}
                <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'mainapp:contacts' %}">Контакты</a>
                </li>
            </ul>
            <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
        </div>
    </div>
</nav>